server:
  port: 18090

spring:
  application:
    name: eureka-client # 应用名称

eureka:
  client:
    service-url:
      # 服务注册地址
      defaultZone: http://peer1:18081/eureka/,http://peer2:18082/eureka/,http://peer3:18083/eureka/

