server:
  port: 18090

spring:
  application:
    name: eureka-client-one # 应用名称

eureka:
  client:
    service-url:
      # 服务注册地址
      defaultZone: http://peer1:18080/eureka/,http://peer2:18081/eureka/,http://peer3:18082/eureka/

