spring:
  application:
    name: eureka-server
server:
  port: 18082
eureka:
  instance:
    hostname: peer3
  server:
    enable-self-preservation: false
  client:
    service-url:
      # 向peer2节点注册自己
      defaultZone: http://peer1:18080/eureka,http://peer2:18081/eureka

