spring:
  application:
    name: eureka-server
server:
  port: 18081
eureka:
  instance:
    hostname: peer2
  server:
    enable-self-preservation: false
  client:
    service-url:
      # 向peer2节点注册自己
      defaultZone: http://peer1:18080/eureka,http://peer3:18082/eureka

