spring:
  application:
    name: eureka-server
server:
  port: 18080
eureka:
  instance:
    hostname: peer1
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false

